"""Add foreign key constraints for referential integrity

Revision ID: 9f28386ec34c
Revises: 62e2378f40de
Create Date: 2026-03-02 10:24:56.446847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f28386ec34c'
down_revision: Union[str, Sequence[str], None] = '62e2378f40de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'quiz_answer', 'quiz_question', ['question_id'], ['question_id'])
    op.create_foreign_key(None, 'quiz_answer', 'students', ['student_id'], ['student_id'])
    op.create_foreign_key(None, 'quiz_answer', 'quiz_attempt', ['attempt_id'], ['attempt_id'])
    op.create_foreign_key(None, 'quiz_attempt', 'students', ['student_id'], ['student_id'])
    op.create_foreign_key(None, 'quiz_plan', 'students', ['student_id'], ['student_id'])
    op.create_foreign_key(None, 'quiz_question', 'students', ['student_id'], ['student_id'])
    op.create_foreign_key(None, 'skill_evidence', 'students', ['student_id'], ['student_id'])
    op.create_foreign_key(None, 'skill_profile_claimed', 'students', ['student_id'], ['student_id'])
    op.create_foreign_key(None, 'student_skill_portfolio', 'students', ['student_id'], ['student_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_skill_portfolio', type_='foreignkey')
    op.drop_constraint(None, 'skill_profile_claimed', type_='foreignkey')
    op.drop_constraint(None, 'skill_evidence', type_='foreignkey')
    op.drop_constraint(None, 'quiz_question', type_='foreignkey')
    op.drop_constraint(None, 'quiz_plan', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempt', type_='foreignkey')
    op.drop_constraint(None, 'quiz_answer', type_='foreignkey')
    op.drop_constraint(None, 'quiz_answer', type_='foreignkey')
    op.drop_constraint(None, 'quiz_answer', type_='foreignkey')
    # ### end Alembic commands ###
